In [1]:
import numpy as np

In [2]:
arr  = np.arange(0,11)

In [3]:
arr + 5 # add 5 to each number of that array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
arr-2 # from initial array do -2 for all

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [7]:
arr+arr # have to be same shape for this

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr/arr # 0/0 will give warning but not error

C:\Users\VARUN ARORA\AppData\Local\Temp\ipykernel_6304\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Numpy is bit special as it does not give dvide by zero error but warning and Nan

In [12]:
1/arr # gives inf for 1/0

C:\Users\VARUN ARORA\AppData\Local\Temp\ipykernel_6304\2183759931.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr # gives inf for 1/0


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [13]:
np.sqrt(arr) # square root of each number

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [14]:
np.sin(arr) # sin of each number

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [16]:
np.log(arr) # log of each number, log0 as -inf and warning

C:\Users\VARUN ARORA\AppData\Local\Temp\ipykernel_6304\1794537551.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # log of each number, log0 as -inf and warning


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr.sum()  # sum of all numbers

55

In [20]:
arr.mean()

5.0

In [21]:
arr.std() # standard deviation

3.1622776601683795

In [24]:
arr_2d =np.arange(0,25).reshape((5,5))

In [28]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr_2d.sum()

300

In [26]:
arr_2d.sum(axis=0) # sum of each column

array([50, 55, 60, 65, 70])

In [27]:
arr_2d.sum(axis=1) # sum of each row

array([ 10,  35,  60,  85, 110])

In [30]:
arr_2d.sum(axis=2) # error as 2d array and no 3rd dimension

AxisError: axis 2 is out of bounds for array of dimension 2