In [1]:
import numpy as np

In [2]:
myList=[1,2,3,4]

In [3]:
my_arr = np.array(myList)
print(my_arr)
type(my_arr)


[1 2 3 4]


numpy.ndarray

In [4]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Numpy methods

In [6]:
np.arange(0,10) # creates a numpy array from 0 to 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,101,2) # creates a numpy array from 0 to 10 with step size 2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [8]:
np.zeros(3) # creates a numpy array of 3 zeros(as float for precision)

array([0., 0., 0.])

In [9]:
np.zeros((2,3)) # 2d array of 3 zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((4,5)) # creates a numpy array of 4 ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,10,5) # creates a numpy array of 10 evenly spaced numbers between 0 and 10 of 5 intervals

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
np.eye(3) # create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.rand(5) # creates a numpy array of 5 random numbers between 0 and 1

array([0.56962182, 0.35451703, 0.36208843, 0.16244751, 0.04853573])

In [14]:
np.random.rand(4,5)  # creates a 4x5 numpy array of random numbers between 0 and 1

array([[0.70488981, 0.31357888, 0.68143281, 0.9649985 , 0.4020442 ],
       [0.0487246 , 0.27769253, 0.59563723, 0.44780967, 0.19499631],
       [0.074384  , 0.66751302, 0.55874508, 0.50534854, 0.56827711],
       [0.08965913, 0.46321539, 0.3956314 , 0.64048777, 0.9736955 ]])

#### Randn to return samples from Standard Distribution

In [15]:
np.random.randn(2) # creates a numpy array of 2 random numbers from a standard normal distribution

array([0.7906905 , 1.61995588])

In [16]:
np.random.randn(2,3)

array([[ 1.45390347,  0.84875577, -1.10010096],
       [ 2.48229927,  1.15970278, -0.08545665]])

In [17]:
np.random.randint(0,101) # creates a random integer between 0 and 100

18

In [18]:
np.random.randint(0,101,10) # creates a numpy array of 10 random integers between 0 and 100

array([71, 56, 14,  2, 49,  2, 37, 44, 65, 22])

In [19]:
np.random.randint(0,101,(3,4)) # creates a numpy 2d array of 10 random integers between 0 and 100

array([[23, 25,  9, 36],
       [63,  5, 33, 61],
       [81, 72, 90, 83]])

You should add a seed to random data so it is actually random

In [20]:
np.random.seed(42) # common in most libraries, make sure to call the next functino in same cell
np.random.rand(4) # these numbers will be same everytime, useful to get same randon numbers, seed is important for same nums to come

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [21]:
arr = np.arange(0,25)

In [22]:
arr.reshape(5,5) # reshape the array to 5x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

Random Arrays and methods

In [23]:
rand_arr = np.random.randint(0,100,10)

In [24]:
rand_arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [25]:
rand_arr.min() # return min value

2

In [26]:
rand_arr.max() # return max value

99

In [27]:
rand_arr.argmax() # return index of max value

5

In [28]:
rand_arr.dtype # return data type of array

dtype('int32')

In [29]:
arr.shape # return shape of array

(25,)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.reshape(25,1) # reshape to 25x1

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [32]:
arr.reshape(5,5) # reshape to 5x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1,25) # reshape to 1x25

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [34]:
test = np.linspace(0,10,101)

In [35]:
test

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])