In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[0:5] # same as arr[:5]

array([0, 1, 2, 3, 4])

In [4]:
arr[4:] # all elements from 4th index

array([4, 5, 6, 7, 8, 9])

Broadcasting

In [5]:
arr[0:5]=100 # assign the numbers as from 0 to 5 indices as 100 not possible otherwise

In [6]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

Slicing

In [7]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
slice = arr[0:5] # slice the array from 0 to 5 indices

In [9]:
slice

array([0, 1, 2, 3, 4])

In [10]:
arr_copy = arr.copy() # copy the array, if arr_copy=arr, then changes in arr_copy will be reflected in arr

In [11]:
arr_copy[-1]=100

In [12]:
arr_copy

array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 100])

Matrices/ 2 dimensional arrays

In [13]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [14]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
arr_2d.shape

(3, 3)

In [16]:
arr_2d[0] # first row

array([ 5, 10, 15])

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
bool_arr = arr > 4 # boolean array

In [19]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [20]:
arr[bool_arr] # all more than 4 elements

array([5, 6, 7, 8, 9])

In [21]:
arr[arr>4] # same as above

array([5, 6, 7, 8, 9])